export const offersData = [{"oferta":"Potatoes - Mini White 3 Oz","ubicacion":"Electronic Components","tipo_contrato":"nunc rhoncus dui vel"},
{"oferta":"Juice - Apple, 1.36l","ubicacion":"Biotechnology: Biological Products (No Diagnostic Substances)","tipo_contrato":"lectus suspendisse potenti in eleifend"},
{"oferta":"Stock - Chicken, White","ubicacion":"Major Banks","tipo_contrato":"primis in faucibus orci luctus"},
{"oferta":"Rice - Brown","ubicacion":"Major Pharmaceuticals","tipo_contrato":"non mi"},
{"oferta":"Fuji Apples","ubicacion":"Restaurants","tipo_contrato":"diam neque"},
{"oferta":"Towels - Paper / Kraft","ubicacion":"n/a","tipo_contrato":"quis"},
{"oferta":"Rye Special Old","ubicacion":"n/a","tipo_contrato":"tristique tortor eu pede"},
{"oferta":"Rye Special Old","ubicacion":"Power Generation","tipo_contrato":"pede morbi porttitor lorem"},
{"oferta":"Soap - Pine Sol Floor Cleaner","ubicacion":"Semiconductors","tipo_contrato":"eu tincidunt in"},
{"oferta":"Lamb - Sausage Casings","ubicacion":"Diversified Commercial Services","tipo_contrato":"pulvinar lobortis est"}]